services:
  flask:
    build: .
    container_name: flask
    ports:
      - "8080:8080"
    volumes:
      - ./app/uploads:/app/app/uploads  
      - ./app:/app/app                 
    environment:
      - MONGO_URI=mongodb://mongo:27017/campus_radio
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db            

volumes:
  mongo_data: