services:
  flask:
    build: .
    container_name: flask
    ports:
      - "8080:8000"
    volumes:
      - ./app/uploads:/app/app/uploads  
      - ./app:/app/app                 
    environment:
      - MONGO_URI=mongodb://mongo:27017/campus_radio
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl/cheersslcert.pem:/etc/nginx/certs/cheersslcert.pem:ro
      - ./nginx/ssl/cheersslkey.pem:/etc/nginx/certs/cheersslkey.pem:ro
    depends_on:
      - flask

         

volumes:
  mongo_data: