version: "3.9"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/hls:/hls
      - ./app/media:/media
      - ./app/uploads:/uploads
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - FFMPEG_HOST=ffmpeg
      - FFMPEG_PORT=9000
    depends_on:
      - ffmpeg
      - mongo

  ffmpeg:
    build:
      context: .
      dockerfile: Dockerfile.ffmpeg
    entrypoint: ["bash", "-c"]
    command: >
      "nc -lk -p 9000 | ffmpeg -y -i - -c:v libx264 -c:a aac -f hls -hls_time 2 -hls_list_size 5 -hls_flags delete_segments /output/stream.m3u8"
    volumes:
      - ./hls:/output
    ports:
      - "9000:9000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
volumes:
  mongo_data: